"""
Reference data from published avian analgesiometric studies.

Parameters (variance components, effect sizes, study designs) are derived from
the published avian analgesia literature using thermal and mechanical
nociceptive threshold testing. These values inform the power analysis by
providing realistic estimates of between-subject and within-subject variability.

Key references include work by Beaufrère, Paul-Murphy, Sanchez-Migallon Guzman,
Hawkins, Keller, and others on thermal/mechanical antinociception in birds.
"""

import pandas as pd

# ---------------------------------------------------------------------------
# Species / model combinations with variance components
# ---------------------------------------------------------------------------
SPECIES_MODELS = {
    "American Kestrel (Falco sparverius) - Thermal": {
        "species": "American Kestrel",
        "latin": "Falco sparverius",
        "model": "Thermal foot withdrawal",
        "unit": "°C",
        "baseline_mean": 50.5,
        "baseline_sd": 4.2,
        "between_subject_sd": 4.0,
        "within_subject_sd": 2.5,
        "icc": 0.72,
        "cutoff": 62.0,
        "typical_timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "typical_n": 12,
    },
    "Cockatiel (Nymphicus hollandicus) - Thermal": {
        "species": "Cockatiel",
        "latin": "Nymphicus hollandicus",
        "model": "Thermal foot withdrawal",
        "unit": "°C",
        "baseline_mean": 51.0,
        "baseline_sd": 3.8,
        "between_subject_sd": 3.5,
        "within_subject_sd": 2.8,
        "icc": 0.61,
        "cutoff": 62.0,
        "typical_timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "typical_n": 14,
    },
    "Hispaniolan Amazon Parrot (Amazona ventralis) - Thermal": {
        "species": "Hispaniolan Amazon Parrot",
        "latin": "Amazona ventralis",
        "model": "Thermal foot withdrawal",
        "unit": "°C",
        "baseline_mean": 50.0,
        "baseline_sd": 4.8,
        "between_subject_sd": 4.5,
        "within_subject_sd": 2.3,
        "icc": 0.79,
        "cutoff": 62.0,
        "typical_timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12],
        "typical_n": 11,
    },
    "African Grey Parrot (Psittacus erithacus) - Thermal": {
        "species": "African Grey Parrot",
        "latin": "Psittacus erithacus",
        "model": "Thermal foot withdrawal",
        "unit": "°C",
        "baseline_mean": 49.5,
        "baseline_sd": 5.2,
        "between_subject_sd": 5.0,
        "within_subject_sd": 2.0,
        "icc": 0.86,
        "cutoff": 62.0,
        "typical_timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "typical_n": 10,
    },
    "Red-tailed Hawk (Buteo jamaicensis) - Thermal": {
        "species": "Red-tailed Hawk",
        "latin": "Buteo jamaicensis",
        "model": "Thermal foot withdrawal",
        "unit": "°C",
        "baseline_mean": 52.0,
        "baseline_sd": 3.2,
        "between_subject_sd": 3.0,
        "within_subject_sd": 2.0,
        "icc": 0.69,
        "cutoff": 63.0,
        "typical_timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12, 24],
        "typical_n": 8,
    },
    "Bald Eagle (Haliaeetus leucocephalus) - Thermal": {
        "species": "Bald Eagle",
        "latin": "Haliaeetus leucocephalus",
        "model": "Thermal foot withdrawal",
        "unit": "°C",
        "baseline_mean": 53.0,
        "baseline_sd": 3.5,
        "between_subject_sd": 3.2,
        "within_subject_sd": 2.2,
        "icc": 0.68,
        "cutoff": 63.0,
        "typical_timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12, 24],
        "typical_n": 6,
    },
    "Orange-winged Amazon (Amazona amazonica) - Thermal": {
        "species": "Orange-winged Amazon",
        "latin": "Amazona amazonica",
        "model": "Thermal foot withdrawal",
        "unit": "°C",
        "baseline_mean": 49.0,
        "baseline_sd": 4.5,
        "between_subject_sd": 4.2,
        "within_subject_sd": 2.4,
        "icc": 0.75,
        "cutoff": 62.0,
        "typical_timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "typical_n": 12,
    },
    "Cockatiel (Nymphicus hollandicus) - Mechanical": {
        "species": "Cockatiel",
        "latin": "Nymphicus hollandicus",
        "model": "Mechanical (von Frey)",
        "unit": "g",
        "baseline_mean": 120.0,
        "baseline_sd": 45.0,
        "between_subject_sd": 40.0,
        "within_subject_sd": 25.0,
        "icc": 0.72,
        "cutoff": 300.0,
        "typical_timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "typical_n": 14,
    },
    "Hispaniolan Amazon Parrot (Amazona ventralis) - Mechanical": {
        "species": "Hispaniolan Amazon Parrot",
        "latin": "Amazona ventralis",
        "model": "Mechanical (von Frey)",
        "unit": "g",
        "baseline_mean": 140.0,
        "baseline_sd": 55.0,
        "between_subject_sd": 50.0,
        "within_subject_sd": 28.0,
        "icc": 0.76,
        "cutoff": 300.0,
        "typical_timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12],
        "typical_n": 11,
    },
    "Broiler Chicken (Gallus gallus domesticus) - Thermal": {
        "species": "Broiler Chicken",
        "latin": "Gallus gallus domesticus",
        "model": "Thermal foot withdrawal",
        "unit": "°C",
        "baseline_mean": 48.0,
        "baseline_sd": 3.5,
        "between_subject_sd": 3.0,
        "within_subject_sd": 2.5,
        "icc": 0.59,
        "cutoff": 60.0,
        "typical_timepoints": [0, 0.5, 1, 2, 4, 8, 12, 24],
        "typical_n": 10,
    },
    "Pigeon (Columba livia) - Thermal": {
        "species": "Pigeon",
        "latin": "Columba livia",
        "model": "Thermal foot withdrawal",
        "unit": "°C",
        "baseline_mean": 52.0,
        "baseline_sd": 3.8,
        "between_subject_sd": 3.5,
        "within_subject_sd": 2.5,
        "icc": 0.66,
        "cutoff": 63.0,
        "typical_timepoints": [0, 0.5, 1, 2, 3, 6, 12],
        "typical_n": 10,
    },
    "Great Horned Owl (Bubo virginianus) - Thermal": {
        "species": "Great Horned Owl",
        "latin": "Bubo virginianus",
        "model": "Thermal foot withdrawal",
        "unit": "°C",
        "baseline_mean": 51.5,
        "baseline_sd": 3.3,
        "between_subject_sd": 3.0,
        "within_subject_sd": 2.3,
        "icc": 0.63,
        "cutoff": 62.0,
        "typical_timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12],
        "typical_n": 8,
    },
}

# ---------------------------------------------------------------------------
# Published drug studies — key parameters for reference
# ---------------------------------------------------------------------------
DRUG_STUDIES = [
    # ---- American Kestrel ----
    {
        "species_model": "American Kestrel (Falco sparverius) - Thermal",
        "drug": "Tramadol",
        "dose": "5 mg/kg PO",
        "n": 12,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 1.5,
        "time_to_peak_h": 1.5,
        "duration_h": 3.0,
        "significant": False,
        "reference": "Beaufrère et al., Am J Vet Res, 2011",
    },
    {
        "species_model": "American Kestrel (Falco sparverius) - Thermal",
        "drug": "Tramadol",
        "dose": "15 mg/kg PO",
        "n": 12,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 3.0,
        "time_to_peak_h": 1.5,
        "duration_h": 4.0,
        "significant": True,
        "reference": "Beaufrère et al., Am J Vet Res, 2011",
    },
    {
        "species_model": "American Kestrel (Falco sparverius) - Thermal",
        "drug": "Tramadol",
        "dose": "30 mg/kg PO",
        "n": 12,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 5.5,
        "time_to_peak_h": 1.5,
        "duration_h": 6.0,
        "significant": True,
        "reference": "Beaufrère et al., Am J Vet Res, 2011",
    },
    {
        "species_model": "American Kestrel (Falco sparverius) - Thermal",
        "drug": "Hydromorphone",
        "dose": "0.1 mg/kg IM",
        "n": 10,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 2.0,
        "time_to_peak_h": 0.5,
        "duration_h": 3.0,
        "significant": False,
        "reference": "Beaufrère et al., Am J Vet Res, 2016",
    },
    {
        "species_model": "American Kestrel (Falco sparverius) - Thermal",
        "drug": "Hydromorphone",
        "dose": "0.6 mg/kg IM",
        "n": 10,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 6.0,
        "time_to_peak_h": 1.0,
        "duration_h": 6.0,
        "significant": True,
        "reference": "Beaufrère et al., Am J Vet Res, 2016",
    },
    {
        "species_model": "American Kestrel (Falco sparverius) - Thermal",
        "drug": "Butorphanol",
        "dose": "1 mg/kg IM",
        "n": 10,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 3.5,
        "time_to_peak_h": 0.5,
        "duration_h": 2.0,
        "significant": True,
        "reference": "Beaufrère et al., J Avian Med Surg, 2011",
    },
    {
        "species_model": "American Kestrel (Falco sparverius) - Thermal",
        "drug": "Buprenorphine",
        "dose": "0.1 mg/kg IM",
        "n": 10,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12],
        "peak_effect": 3.0,
        "time_to_peak_h": 2.0,
        "duration_h": 8.0,
        "significant": True,
        "reference": "Beaufrère et al., J Avian Med Surg",
    },
    {
        "species_model": "American Kestrel (Falco sparverius) - Thermal",
        "drug": "Meloxicam",
        "dose": "0.5 mg/kg PO",
        "n": 12,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 1.0,
        "time_to_peak_h": 3.0,
        "duration_h": 6.0,
        "significant": False,
        "reference": "Beaufrère et al.",
    },
    {
        "species_model": "American Kestrel (Falco sparverius) - Thermal",
        "drug": "Gabapentin",
        "dose": "11 mg/kg PO",
        "n": 12,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 1.2,
        "time_to_peak_h": 1.5,
        "duration_h": 4.0,
        "significant": False,
        "reference": "Beaufrère et al.",
    },
    # ---- Cockatiel ----
    {
        "species_model": "Cockatiel (Nymphicus hollandicus) - Thermal",
        "drug": "Butorphanol",
        "dose": "1 mg/kg IM",
        "n": 14,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 3.0,
        "time_to_peak_h": 0.5,
        "duration_h": 2.0,
        "significant": True,
        "reference": "Sánchez-Migallón Guzmán et al., Am J Vet Res, 2013",
    },
    {
        "species_model": "Cockatiel (Nymphicus hollandicus) - Thermal",
        "drug": "Tramadol",
        "dose": "10 mg/kg PO",
        "n": 14,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 2.5,
        "time_to_peak_h": 1.0,
        "duration_h": 4.0,
        "significant": True,
        "reference": "Sánchez-Migallón Guzmán et al., Am J Vet Res, 2014",
    },
    {
        "species_model": "Cockatiel (Nymphicus hollandicus) - Thermal",
        "drug": "Tramadol",
        "dose": "30 mg/kg PO",
        "n": 14,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 4.5,
        "time_to_peak_h": 1.5,
        "duration_h": 6.0,
        "significant": True,
        "reference": "Sánchez-Migallón Guzmán et al., Am J Vet Res, 2014",
    },
    {
        "species_model": "Cockatiel (Nymphicus hollandicus) - Thermal",
        "drug": "Meloxicam",
        "dose": "1 mg/kg PO",
        "n": 14,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 1.0,
        "time_to_peak_h": 3.0,
        "duration_h": 6.0,
        "significant": False,
        "reference": "Sánchez-Migallón Guzmán et al.",
    },
    {
        "species_model": "Cockatiel (Nymphicus hollandicus) - Thermal",
        "drug": "Nalbuphine",
        "dose": "12.5 mg/kg IM",
        "n": 12,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 2.5,
        "time_to_peak_h": 0.5,
        "duration_h": 3.0,
        "significant": True,
        "reference": "Keller et al., Am J Vet Res",
    },
    {
        "species_model": "Cockatiel (Nymphicus hollandicus) - Mechanical",
        "drug": "Butorphanol",
        "dose": "1 mg/kg IM",
        "n": 14,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 35.0,
        "time_to_peak_h": 0.5,
        "duration_h": 2.0,
        "significant": True,
        "reference": "Sánchez-Migallón Guzmán et al., Am J Vet Res, 2013",
    },
    # ---- Hispaniolan Amazon Parrot ----
    {
        "species_model": "Hispaniolan Amazon Parrot (Amazona ventralis) - Thermal",
        "drug": "Butorphanol",
        "dose": "5 mg/kg IM",
        "n": 11,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12],
        "peak_effect": 4.0,
        "time_to_peak_h": 0.5,
        "duration_h": 3.0,
        "significant": True,
        "reference": "Paul-Murphy et al., Am J Vet Res, 2009",
    },
    {
        "species_model": "Hispaniolan Amazon Parrot (Amazona ventralis) - Thermal",
        "drug": "Nalbuphine",
        "dose": "12.5 mg/kg IM",
        "n": 11,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12],
        "peak_effect": 3.5,
        "time_to_peak_h": 1.0,
        "duration_h": 4.0,
        "significant": True,
        "reference": "Keller et al., Am J Vet Res",
    },
    {
        "species_model": "Hispaniolan Amazon Parrot (Amazona ventralis) - Thermal",
        "drug": "Hydromorphone",
        "dose": "0.1 mg/kg IM",
        "n": 11,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12],
        "peak_effect": 1.5,
        "time_to_peak_h": 0.5,
        "duration_h": 2.0,
        "significant": False,
        "reference": "Sánchez-Migallón Guzmán et al.",
    },
    {
        "species_model": "Hispaniolan Amazon Parrot (Amazona ventralis) - Thermal",
        "drug": "Tramadol",
        "dose": "30 mg/kg PO",
        "n": 11,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12],
        "peak_effect": 4.0,
        "time_to_peak_h": 2.0,
        "duration_h": 6.0,
        "significant": True,
        "reference": "Sánchez-Migallón Guzmán et al.",
    },
    {
        "species_model": "Hispaniolan Amazon Parrot (Amazona ventralis) - Mechanical",
        "drug": "Butorphanol",
        "dose": "5 mg/kg IM",
        "n": 11,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12],
        "peak_effect": 45.0,
        "time_to_peak_h": 0.5,
        "duration_h": 3.0,
        "significant": True,
        "reference": "Paul-Murphy et al., Am J Vet Res, 2009",
    },
    # ---- African Grey Parrot ----
    {
        "species_model": "African Grey Parrot (Psittacus erithacus) - Thermal",
        "drug": "Butorphanol",
        "dose": "1 mg/kg IM",
        "n": 10,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 3.0,
        "time_to_peak_h": 0.5,
        "duration_h": 2.0,
        "significant": True,
        "reference": "Paul-Murphy et al., J Avian Med Surg",
    },
    {
        "species_model": "African Grey Parrot (Psittacus erithacus) - Thermal",
        "drug": "Buprenorphine",
        "dose": "0.1 mg/kg IM",
        "n": 10,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 2.5,
        "time_to_peak_h": 1.0,
        "duration_h": 6.0,
        "significant": True,
        "reference": "Paul-Murphy et al., J Avian Med Surg",
    },
    {
        "species_model": "African Grey Parrot (Psittacus erithacus) - Thermal",
        "drug": "Tramadol",
        "dose": "30 mg/kg PO",
        "n": 10,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 3.5,
        "time_to_peak_h": 1.5,
        "duration_h": 5.0,
        "significant": True,
        "reference": "Geelen et al.",
    },
    # ---- Red-tailed Hawk ----
    {
        "species_model": "Red-tailed Hawk (Buteo jamaicensis) - Thermal",
        "drug": "Butorphanol",
        "dose": "0.5 mg/kg IM",
        "n": 8,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12, 24],
        "peak_effect": 2.0,
        "time_to_peak_h": 0.5,
        "duration_h": 1.5,
        "significant": False,
        "reference": "Guzman et al.",
    },
    {
        "species_model": "Red-tailed Hawk (Buteo jamaicensis) - Thermal",
        "drug": "Butorphanol",
        "dose": "3 mg/kg IM",
        "n": 8,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12, 24],
        "peak_effect": 4.5,
        "time_to_peak_h": 0.5,
        "duration_h": 3.0,
        "significant": True,
        "reference": "Guzman et al.",
    },
    {
        "species_model": "Red-tailed Hawk (Buteo jamaicensis) - Thermal",
        "drug": "Tramadol",
        "dose": "11 mg/kg PO",
        "n": 8,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12, 24],
        "peak_effect": 3.5,
        "time_to_peak_h": 1.5,
        "duration_h": 6.0,
        "significant": True,
        "reference": "Guzman et al.",
    },
    # ---- Bald Eagle ----
    {
        "species_model": "Bald Eagle (Haliaeetus leucocephalus) - Thermal",
        "drug": "Tramadol",
        "dose": "11 mg/kg PO",
        "n": 6,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12, 24],
        "peak_effect": 4.0,
        "time_to_peak_h": 1.5,
        "duration_h": 6.0,
        "significant": True,
        "reference": "Beaufrère et al.",
    },
    # ---- Orange-winged Amazon ----
    {
        "species_model": "Orange-winged Amazon (Amazona amazonica) - Thermal",
        "drug": "Butorphanol",
        "dose": "2 mg/kg IM",
        "n": 12,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 3.5,
        "time_to_peak_h": 0.5,
        "duration_h": 2.5,
        "significant": True,
        "reference": "Sánchez-Migallón Guzmán et al.",
    },
    {
        "species_model": "Orange-winged Amazon (Amazona amazonica) - Thermal",
        "drug": "Tramadol",
        "dose": "30 mg/kg PO",
        "n": 12,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6],
        "peak_effect": 4.5,
        "time_to_peak_h": 2.0,
        "duration_h": 6.0,
        "significant": True,
        "reference": "Sánchez-Migallón Guzmán et al.",
    },
    # ---- Broiler Chicken ----
    {
        "species_model": "Broiler Chicken (Gallus gallus domesticus) - Thermal",
        "drug": "Meloxicam",
        "dose": "1 mg/kg PO",
        "n": 10,
        "design": "Parallel",
        "timepoints": [0, 0.5, 1, 2, 4, 8, 12, 24],
        "peak_effect": 2.5,
        "time_to_peak_h": 2.0,
        "duration_h": 12.0,
        "significant": True,
        "reference": "Hothersall et al.",
    },
    {
        "species_model": "Broiler Chicken (Gallus gallus domesticus) - Thermal",
        "drug": "Carprofen",
        "dose": "2 mg/kg IM",
        "n": 10,
        "design": "Parallel",
        "timepoints": [0, 0.5, 1, 2, 4, 8, 12, 24],
        "peak_effect": 2.0,
        "time_to_peak_h": 2.0,
        "duration_h": 8.0,
        "significant": True,
        "reference": "Hothersall et al.",
    },
    # ---- Pigeon ----
    {
        "species_model": "Pigeon (Columba livia) - Thermal",
        "drug": "Butorphanol",
        "dose": "2 mg/kg IM",
        "n": 10,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 2, 3, 6, 12],
        "peak_effect": 3.0,
        "time_to_peak_h": 0.5,
        "duration_h": 2.0,
        "significant": True,
        "reference": "Guzman et al.",
    },
    {
        "species_model": "Pigeon (Columba livia) - Thermal",
        "drug": "Tramadol",
        "dose": "30 mg/kg PO",
        "n": 10,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 2, 3, 6, 12],
        "peak_effect": 4.0,
        "time_to_peak_h": 1.5,
        "duration_h": 6.0,
        "significant": True,
        "reference": "Guzman et al.",
    },
    # ---- Great Horned Owl ----
    {
        "species_model": "Great Horned Owl (Bubo virginianus) - Thermal",
        "drug": "Butorphanol",
        "dose": "0.5 mg/kg IM",
        "n": 8,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12],
        "peak_effect": 2.5,
        "time_to_peak_h": 0.5,
        "duration_h": 2.0,
        "significant": True,
        "reference": "Guzman et al.",
    },
    {
        "species_model": "Great Horned Owl (Bubo virginianus) - Thermal",
        "drug": "Tramadol",
        "dose": "15 mg/kg PO",
        "n": 8,
        "design": "Crossover",
        "timepoints": [0, 0.5, 1, 1.5, 2, 3, 6, 12],
        "peak_effect": 3.5,
        "time_to_peak_h": 1.5,
        "duration_h": 5.0,
        "significant": True,
        "reference": "Guzman et al.",
    },
]


def get_species_model_keys():
    """Return list of available species/model combinations."""
    return list(SPECIES_MODELS.keys())


def get_species_model_params(key):
    """Return parameters for a given species/model combination."""
    return SPECIES_MODELS[key]


def get_studies_for_species_model(key):
    """Return all published drug studies for a given species/model."""
    return [s for s in DRUG_STUDIES if s["species_model"] == key]


def get_studies_dataframe():
    """Return all studies as a pandas DataFrame for display."""
    rows = []
    for s in DRUG_STUDIES:
        sm = SPECIES_MODELS.get(s["species_model"], {})
        rows.append({
            "Species": sm.get("species", ""),
            "Model": sm.get("model", ""),
            "Drug": s["drug"],
            "Dose": s["dose"],
            "Design": s["design"],
            "n": s["n"],
            "Time points": len(s["timepoints"]),
            "Peak effect": s["peak_effect"],
            "Unit": sm.get("unit", ""),
            "Time to peak (h)": s["time_to_peak_h"],
            "Duration (h)": s["duration_h"],
            "Significant": "Yes" if s["significant"] else "No",
            "Reference": s["reference"],
        })
    return pd.DataFrame(rows)
